name: NaN
description: Blog of Liam Jongsu Kim
meta_description: "Personal pages, Fluid Dynamics, Scientific Computing"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 20
baseurl: /
domain_name: 'http://blog.liam.kim'
google_analytics: 'UA-19932832-3'
gems: [jekyll-paginate]
math_engine_opts: {
  preview: true
}

# Details for the RSS feed generator
url:            'http://blog.liam.kim'
author:         'Liam Jongsu Kim'
